### ISSUE TITLE
Spec failed

### ISSUE THREAD

**Issue by DanielBoettner** [centosadmin/redmine_recurring_tasks#15]
When doing 

> RAILS_ENV=production bundle exec rake redmine_recurring_tasks:exec

to test. 

The output is: 

> spec failed.
> [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
> [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

Maybe you can give me a hint on where to investigate the error.

EDIT:

After adding "rspec-core" to the redmine gemfile.

The spec no longer fails.
Output is now, 3 lines of  

> [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

Any hint on where to check why nothing is happening?

**Comment by DanielBoettner** [comment]
Changed the comand to

>  bundle exec rake redmine_recurring_tasks:exec

Output after this 

> [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
> [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
> [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
> rake aborted!
> Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
> /opt/bitnami/apps/redmine/htdocs/app/models/custom_field.rb:36:in `<class:CustomField>'
> /opt/bitnami/apps/redmine/htdocs/app/models/custom_field.rb:18:in `<top (required)>'
> /opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:90:in `field_attributes'
> /opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:93:in `<class:Base>'
> /opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:50:in `<module:FieldFormat>'
> /opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:21:in `<module:Redmine>'
> /opt/bitnami/apps/redmine/htdocs/lib/redmine/field_format.rb:20:in `<top (required)>'
> /opt/bitnami/apps/redmine/htdocs/lib/redmine.rb:40:in `<top (required)>'
> /opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:6:in `<top (required)>'
> /opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
> Tasks: TOP => redmine_recurring_tasks:exec => environment
> (See full trace by running task with --trace)

**Comment by olemskoi** [comment]
Did you setup scheduler https://github.com/centosadmin/redmine_recurring_tasks#schedulers ?

You can try to run by hand:
```
cd {REDMINE_ROOT}
bundle exec rake redmine_recurring_tasks:exec
```
