### ISSUE TITLE
Create a recurring task

### ISSUE THREAD

**Issue by batje** [centosadmin/redmine_recurring_tasks#16]
I installed the plugin, i can see it in the Admin section and I can change the setting. I also can enable the plugin in the project settings. And I run the cronjob.

But when I create or edit an issue, I do not see anything that points to a recurring task. How do I create one?

(that would be really useful in the README.md)

**Comment by constXife** [comment]
Thanks for using our plugin. I updated readme. Take a look, please. If you will still have questions or new proposals - you are welcome to ask.
