### ISSUE TITLE
Schedule!

### ISSUE THREAD

**Issue by morevalar** [centosadmin/redmine_recurring_tasks#18]
Hi! Can you add a more understandable schedule. Did not found how to get a schedule for every 5th December of the year for example. Thank you!

**Comment by constXife** [comment]
Hi! You may make like this.

Go to the issue, find "Schedule" section and link "Add" right from it. Click on it. Then click on proper checkboxes like on image. If your form look's not like this, grab plugin from develop git branch.

<img width="1249" alt="2017-09-20 23 43 44" src="https://user-images.githubusercontent.com/870327/30656358-0d850e2e-9e5e-11e7-85e2-ceaac6fc71d1.png">

If you have some vision about plugin UI should be, please, share with us, we will appreciate it.
