### ISSUE TITLE
Автор задачи Аноним

### ISSUE THREAD

**Issue by radist** [centosadmin/redmine_recurring_tasks#2]
Логичнее было бы копировать автора. Либо добавить в настройки возможность указать автора.

**Comment by olemskoi** [comment]
Все сделаем.

**Comment by olemskoi** [comment]
Да, всё верно. Мы использовали функцию Redmine для дубликата задач, но там в качестве автора берётся текущий пользователь системы, а так как у нас консольное приложение, то по умолчанию текущий пользователь системы — это аноним. Текущее поведение поправили на нужное и пользователь задачи теперь сохраняется. Также добавили соответствующие тесты.
