### ISSUE TITLE
Support more recurring option

### ISSUE THREAD

**Issue by n2nlopes** [centosadmin/redmine_recurring_tasks#20]
Hi,

Is it possible to support more recurring options to align with Scrum sprint time? For example, I want to spawn new tasks automatically to handle work for sprint planning, sprint retrospective, sprint review every 2 weeks for 2-week sprint? 

Thanks a bunch. 
Nora.

**Comment by olemskoi** [comment]
This plugin copies template task as is. Try to make task as you want, it should work.
