### ISSUE TITLE
How to list recurred/scheduled task?

### ISSUE THREAD

**Issue by mutluozel** [centosadmin/redmine_recurring_tasks#21]
Hello,

I have to implemented recurring tasks plugin for redmine and scheduled some of tasks and will recure it but i don’t know; how can i list or check or cancel or monitor for scheduled tasks ?

Many thanks for your help

Mutlu

**Comment by olemskoi** [comment]
Did you run whenever?

**Comment by mutluozel** [comment]
No i am wait for crontab will work when getting the period!..

**Comment by mutluozel** [comment]
anybody help me!

**Comment by olemskoi** [comment]
Please read install instructions in readme. You have to setup cron (run whenever) to initialize cron.
