### ISSUE TITLE
create multiple tasks when trigger it

### ISSUE THREAD

**Issue by mutluozel** [centosadmin/redmine_recurring_tasks#22]
Hello,

Today triggered, redmine_recurring_tasks from crontab and repeat same task in a 3-4 hours.

Normally i hope create only a task when trigger the crontab, but now i have seen; in 3-4 hours, 5 mins period created multiple same tasks why ?

by the way i didnt see, scheduled tasks ! how can i check, which tasks are scheduled ?

**Comment by olemskoi** [comment]
This is a bug. It will be fixed in a few days.

**Comment by olemskoi** [comment]
We have fixed this bug. You can check it from develop branch.
