### ISSUE TITLE
НЕ РАБОТАЕТ ПЛАГИН ПОЧИНИТЕ!!!

### ISSUE THREAD

**Issue by aroun** [centosadmin/redmine_recurring_tasks#27]
Парни, а зачем ему девелоперская база?

![2018-02-21_16-20-36](https://user-images.githubusercontent.com/4037513/36482168-6a5156e2-1723-11e8-997b-9ec3c49cd27a.png)

**Comment by olemskoi** [comment]
А вы указали RAILS_ENV?

**Comment by aroun** [comment]
Я то указал, но вы же явно тогда тоже указывайте в описании

![2018-02-21_16-27-31](https://user-images.githubusercontent.com/4037513/36482383-2e8df8ee-1724-11e8-8bb7-b26191ba58bd.png)

**Comment by aroun** [comment]
Также неплохо было бы подробней рассказать как на убунте это разворачивается, я понимаю что CentOS наше все, но тем не менее

**Comment by olemskoi** [comment]
Мы всегда рады pull request-ам с улучшениями документации.

Получилось? Тикет можно закрывать?

**Comment by aroun** [comment]
Нет, кавычек не хватает 

![2018-02-21_16-35-44](https://user-images.githubusercontent.com/4037513/36482748-4dc5fdf0-1725-11e8-9921-db71012e161f.png)

**Comment by aroun** [comment]
После exec должна быть ' наверно....

**Comment by aroun** [comment]
Вы не хотите в частном порядке помочь настроить на убунте ваш плагин?
А я бы помог вам с документацией?

**Comment by olemskoi** [comment]
Какую команду и под каким пользователем выполняете? Установлен ли bundle?

**Comment by dmitrygusakov** [comment]
У меня заработало в кроне только по следующей схеме, создал скрип /home/recurring_tasks.sh

#!/bin/bash

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin"
export PATH=$PATH:/usr/local/rubygems/bin:/usr/local/rubygems/gems/bin
export RUBYLIB=/usr/local/rubygems/lib
export GEM_HOME=/usr/local/rubygems/gems
/bin/bash -l -c 'cd /opt/redmine && bundle exec rake redmine_recurring_tasks:exec RAILS_ENV=production'

потом
$ crontab -e
и туда добавил
*/1 * * * * /home/recurring_tasks.sh >/tmp/redmine_recurring_tasks.log 2>&1

**Comment by olemskoi** [comment]
Скорее всего это вопросы, связанные с окружением / настройкой для работы с ruby / bundle.
