### ISSUE TITLE
Не могу найти "Schedule section"

### ISSUE THREAD

**Issue by alexg-nn** [centosadmin/redmine_recurring_tasks#29]
Добрый день.
Пытаюсь заставить работать ваш плагин с такой конфигурацией:
```
Environment:
  Redmine version                3.3.0.stable.15842
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  plantuml                       0.3.0
  redmine_ckeditor               1.1.4
  redmine_lightbox2              0.3.1
  redmine_open_links_in_new_window 0.0.3
  redmine_per_project_formatting 0.0.4
  redmine_recurring_tasks        0.2.0
```

Плагин установился по вашей инструкции без проблем, он есть в списке модулей редмайна, есть галочка Redmine Recurring Tasks в модулях проекта, но нигде не нахожу описанного в мануале
"Schedule section" хоть стреляйте. Версию плагина брал с мастер ветки.

**Comment by dmitrygusakov** [comment]
Доброго.
Вот Вы создали задачу, потом начинаете её редактировать и внизу между разделами "Описание" и "Подзадачи" у Вас появилось "Расписание" ?

**Comment by alexg-nn** [comment]
Посыпаю голову пеплом, действительно есть такая. Спасибо большое.

**Comment by constXife** [comment]
Добавил русское ридми. Может облегчит знакомство с плагином в первый раз.
