### ISSUE TITLE
Unable to see Schedule / Calendar button in issue Creation

### ISSUE THREAD

**Issue by ptsakyrellis** [centosadmin/redmine_recurring_tasks#40]
Hi, 

I followed the readme and installed the plugin + cron successfully. I edited my project settings to enable the recurring task module, but i don't see any schedule section in the issue creation form. 

I also set the permissions for my role to be able to do the recurring tasks actions. 

Do you know what i am missing ? 

I'm using the plugin over a french translation version of redmine with these settings : 

> Environment:
>   Redmine version                3.3.4.stable
>   Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.6.11
>   Git                            1.7.1
>   Filesystem                     
> Redmine plugins:
>   redmine_agile                  1.4.4
>   redmine_checklists             3.1.10
>   redmine_messenger              0.9.9
>   redmine_recurring_tasks        0.2.2
>   redmine_redsun                 2.1.1

**Comment by ptsakyrellis** [comment]
And here is my issue creation page : 
![issue_creation](https://user-images.githubusercontent.com/13604355/38991968-970140e2-43df-11e8-841f-3791e27ecd04.gif)

Thanks for your time.

**Comment by ptsakyrellis** [comment]
And here is my issue creation page : 

![issue](https://user-images.githubusercontent.com/13604355/38992037-ce26e586-43df-11e8-98ad-0369984cbc8a.jpg)

**Comment by olemskoi** [comment]
Did you enable module "Redmine Recurring Tasks" in this project?

Please send screenshot of created task.

**Comment by ptsakyrellis** [comment]
Yes I did, but I understant now : it's only visible once the issue is created. You should maybe add that to the readme, that the "Schedul section" is visible on the show/edit page of the issue and not on the new issue form. 

Thanks for your super quick answer ! :+1:
