### ISSUE TITLE
No way to see the plugin in action

### ISSUE THREAD

**Issue by halender** [centosadmin/redmine_recurring_tasks#41]
I've already installed the plugin successfully on a Redmine 3.3.3. I can see the plugin in Admin options. I can activate the plugin in the projects. 
But after being activated in a project, I cannot see the way to configure or create any recurring issue.

**Comment by terah** [comment]
I have the exact same issue.

**Comment by terah** [comment]
Ah.. @halender  see here: https://github.com/centosadmin/redmine_recurring_tasks/issues/40#issuecomment-382719998

**Comment by halender** [comment]
Thank you so much, @terah !!  You're right! It's there!
